name: check
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v4.0.0
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum
      - name: Build project
        run: make build
